kind: pipeline
name: default

steps:
- name: build
  image: golang:1.13
  environment:
    GOFLAGS: -mod=vendor
  commands:
  - apt-get update && apt-get install -y upx
  - make buildall VERSION=${DRONE_TAG##v}
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: build/*
    checksum:
      - sha256
      - sha512

trigger:
  event:
  - tag
