---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.13
  commands:
  - apt-get update && apt-get install -y upx
  - make build_all VERSION=${DRONE_TAG##v}
  environment:
    GOFLAGS: -mod=vendor

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    - sha512
    files: build/*

trigger:
  event:
  - tag

...
