log_level = "debug"
log_format = "text" # output log format (you can use text or json)
auto_download_updates = false  # if true service will download update and exit

[core]
    id = "" # id of edge
    rpc_timeout = "2m" # how long core should wait response from connector before return timeout error


    [core.cloud]
    url = "https://sandbox.rightech.io/api/v1"
    # cloud jwt access token
    # minimal scope should be
    #
    # GET models/:id
    # GET objects/:id
     token = ""  # cloud jwt access token

    [core.mqtt]
    # if cert_file and key_path provided core will be use tls connection
    # in this case make sure your url start with tls://
    url = "tls://sandbox.rightech.io:8883"
    cert_file = "" # mqtt certificate file path
    key_path = "" # mqtt key file path
    
[opcua]
    endpoint = "opc.tcp://localhost:4840"
    encryption = "Basic256Sha256"   # required for encrypted servers only, "Basic256Sha", "Basic256", "Basic128Rsa15" supported
    mode = "SignAndEncrypt"         # required for encrypted servers only, "None", "Sign", "SignAndEncrypt" supported
    server_cert = "cert.pem"        # required for encrypted servers only, path to .pem certificate 
    server_key = "key.pem"          # required for encrypted servers only, path to .pem key 
