log_level = "debug"
log_format = "text" # output log format (you can use text or json)
auto_download_updates = false  # if true service will download update and exit

[core]
    id = "" # id of edge
    rpc_timeout = "2m" # how long core should wait response from connector before return timeout error


    [core.cloud]
    url = "https://sandbox.rightech.io/api/v1"
    # cloud jwt access token
    # minimal scope should be
    #
    # GET models/:id
    # GET objects/:id
    token = ""  # cloud jwt access token

    [core.mqtt]
    # if cert_file and key_path provided core will be use tls connection
    # in this case make sure your url start with tls://
    url = "tls://sandbox.rightech.io:8883"
    cert_file = "" # mqtt certificate file path
    key_path = "" # mqtt key file path
    
[snmp]
    host_port="127.0.0.1:161"
    community=""                  # community string, required for v2c only
    version=""                    # version of SNMP ("2c" or "3")
    mode = "authPriv"             # mode of encryption ("authPriv", "authNoPriv", "NoauthNoPriv"), required for v3 only
    auth_protocol = "MD5"         # "MD5" and "SHA" supported, required for v3 only (if necessary)
    auth_key = ""                 # required for v3 only (if necessary)
    priv_protocol = "DES"         # "DES" and "AES" supported, required for v3 only (if necessary)
    priv_key = ""                 # required for v3 only (if necessary)
    security_name = ""            # required for v3 only
