name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Build binaries
        run: make build_all VERSION=${GITHUB_REF#refs/tags/v}
        env:
          GOFLAGS: -mod=vendor
      - name: Calculate binaries hash
        run: |
          cd build
          sha256sum * > sha256sum.txt
      - name: Save binaries
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: build/*
      - name: Create Github release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/*
          gzip: false
