name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - uses: actions/cache@v1
        id: upx
        with:
          path: upx
          key: ${{ runner.os }}-upx-3.95
      - name: Install upx
        if: steps.upx.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz
          tar -xJf upx-3.95-amd64_linux.tar.xz
          mv upx-3.95-amd64_linux upx
      - name: Prepare build
        run: sudo ln -s $(pwd)/upx/upx /usr/bin/upx
      - name: Build binaries
        run: make build_all VERSION=${GITHUB_REF#refs/tags/v}
        env:
          GOFLAGS: -mod=vendor
      - name: Calculate binaries hash
        run: |
          cd build
          sha256sum * > sha256sum.txt
      - name: Create Github release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: build/*
          gzip: false
